name: Deploy to vps

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 200.234.228.166
          port: 2222
          username: danny79k
          key: ${{ secrets.ecogavia }}
          script: "cd /var/www/html/Ecogavia; git pull origin master; php artisan route:clear; sudo service php8.3-fpm reload;npm run build"
